name: RealEstate
main: pro.homiecraft.realEstate
version: 1.0
author: GudfareN
website: homiecraft.pro
depend: [Vault]

commands:
   estate:
      description: Estate
   es:
      description: Estate